GSTEducationERP/Controllers/AccountantController.cs
using GSTEducationERPLibrary.Account;
using GSTEducationERPLibrary.Accountant;
using GSTEducationERPLibrary.Trainer;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Util;

namespace GSTEducationERP.Controllers
{
    public class AccountantController : Controller
    {
        private readonly BALAccountant objbal = new BALAccountant();
        private readonly Accountant objac = new Accountant();
        public class BreadcrumbItem
        {
            public string Name { get; set; }
            public string Url { get; set; }
        }
        #region // Vouvcher
        // GET: Accountant
        public ActionResult AccountantDashboardAsyncSGS()
        {
            return View();
        }
        private async Task<List<Accountant>> GetVouchersList()
        {
            Accountant objT = new Accountant();
            DataSet ds = await objbal.GetVoucher(objT);
            List<Accountant> studentsList = new List<Accountant>();
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                studentsList.Add(new Accountant
                {
                    VoucherId = Convert.ToInt32(dr["VoucherId"]),
                    VoucherCode = dr["VoucherCode"].ToString(),
                    VendorName = dr["VendorName"].ToString(),
                    Amount = float.Parse(dr["Amount"].ToString()),
                    AmountPaidTo = dr["AmountPaidTo"].ToString(),
                    Description = dr["Description"].ToString(),
                    PaymentMode = dr["PaymentMode"].ToString(),
                    BankId = Convert.ToInt32(dr["BankId"]),
                    ReceiverBankAccountNumber = Convert.ToInt64(dr["ReceiverBankAccountNumber"]),
                    ReceiverBankAccountHolderName = dr["ReceiverBankAccountHolderName"].ToString(),
                    ReceiverBankIFSCCode = dr["ReceiverBankIFSCCode"].ToString(),
                    ReceiverBankName = dr["ReceiverBankName"].ToString(),
                    Balance = float.Parse(dr["Balance"].ToString()),
                    Currency = dr["Currency"].ToString(),
                    TransactionId = dr["TransactionId"].ToString(),
                    VoucherType = dr["VoucherType"].ToString(),
                    VoucherDate = DateTime.Parse(dr["VoucherDate"].ToString()),
                    StaffCode = dr["StaffCode"].ToString(),
                    StatusId = Convert.ToInt32(dr["StatusId"])
                });
            }
            return studentsList;
        }
        [HttpGet]
        public async Task<ActionResult> ListAllPurchaceAsyncSGS()
        {

            //List<Accountant> vouchers = await GetVouchersList();
            if (Session["StaffCode"] == null)
            {
                return await Task.Run(() => RedirectToAction("Login", "Account"));
            } else
            {
                return View();
            }
        }



        [HttpGet]
        public async Task<ActionResult> RegisterTestAsycTS()
        {
            //List<Accountant> vouchers = await GetVouchersList();
            if (Session["StaffCode"] == null)
            {
                return await Task.Run(() => RedirectToAction("Login", "Account"));
            } else
            {
                return View();
            }
        }
        [HttpGet]
        public async Task<ActionResult> ListAllVouchersAsyncSGS()
        {
            //List<Accountant> vouchers = await GetVouchersList();
            if (Session["StaffCode"] == null)
            {
                return await Task.Run(() => RedirectToAction("Login", "Account"));
            } else
            {

                return View();
            }
        }


        [HttpGet]
        public async Task<ActionResult> ListVoucherAsyncSGS()
        {
            if (Session["StaffCode"] == null)
            {
                return RedirectToAction("Login", "Account"); // Redirect to login page if staff code is not found in session
            } else
            {
                string staffCode = Session["StaffCode"].ToString(); // Retrieve staff code from session
                                                                    //string branchCode = Session["BranchCode"].ToString(); // Retrieve branch code from session

                DataSet ds = new DataSet();

                // Pass staff code and branch code to the method for fetching tests
                ds = await objbal.ListVoucherAsyncSGS();

                Accountant objtr1 = new Accountant();
                List<Accountant> AddExpense1 = new List<Accountant>();

                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    Accountant objtn = new Accountant
                    {
                        VoucherId = row.IsNull("VoucherId") ? 0 : Convert.ToInt32(row["VoucherId"]),
                        VoucherCode = row.IsNull("VoucherCode") ? string.Empty : row["VoucherCode"].ToString(),
                        VendorName = row.IsNull("VendorName") ? string.Empty : row["VendorName"].ToString(),
                        Amount = row.IsNull("Amount") ? 0.0f : float.Parse(row["Amount"].ToString()),
                        AmountPaidTo = row.IsNull("StaffName") ? string.Empty : row["StaffName"].ToString(),
                        Description = row.IsNull("Description") ? string.Empty : row["Description"].ToString(),
                        PaymentMode = row.IsNull("PaymentMode") ? string.Empty : row["PaymentMode"].ToString(),
                        BankId = row.IsNull("BankId") ? 0 : Convert.ToInt32(row["BankId"]),
                        ReceiverBankAccountNumber = row.IsNull("ReceiverBankAccountNumber") ? 0 : Convert.ToInt64(row["ReceiverBankAccountNumber"].ToString()),
                        ReceiverBankAccountHolderName = row.IsNull("ReceiverBankAccountHolderName") ? string.Empty : row["ReceiverBankAccountHolderName"].ToString(),
                        ReceiverBankIFSCCode = row.IsNull("ReceiverBankIFSCCode") ? string.Empty : row["ReceiverBankIFSCCode"].ToString(),
                        ReceiverBankName = row.IsNull("ReceiverBankName") ? string.Empty : row["ReceiverBankName"].ToString(),
                        Balance = row.IsNull("Balance") ? 0.0f : float.Parse(row["Balance"].ToString()),
                        Currency = row.IsNull("Currency") ? string.Empty : row["Currency"].ToString(),
                        TransactionId = row.IsNull("TransactionId") ? string.Empty : row["TransactionId"].ToString(),
                        VoucherType = row.IsNull("Status") ? string.Empty : row["Status"].ToString(),
                        VoucherDate = row.IsNull("VoucherDate") ? DateTime.MinValue : DateTime.Parse(row["VoucherDate"].ToString()),
                        StaffCode = row.IsNull("StaffCode") ? string.Empty : row["StaffCode"].ToString(),
                        StatusId = row.IsNull("StatusId") ? 0 : Convert.ToInt32(row["StatusId"])
                    };

                    AddExpense1.Add(objtn);
                }

                objtr1.lstVoucher = AddExpense1;

                List<BreadcrumbItem> breadcrumbs = new List<BreadcrumbItem>
            {
                //new BreadcrumbItem { Name = "Home", Url = "/" },
                new BreadcrumbItem { Name = "TrainerDashboard", Url = "TrainerDashboardAsyncTS/Trainer" },
               new BreadcrumbItem { Name = "Test Managment", Url = "ListTestManagementAsynchTS/Trainer" }, // Adjust URL as needed
            };

                ViewBag.Breadcrumbs = breadcrumbs;
                return PartialView("ListVoucherAsyncSGS", objtr1);
            }
        }


        [HttpGet]
        public async Task<ActionResult> ListPendingVoucherAsyncSGS()
        {
            if (Session["StaffCode"] == null)
            {
                return RedirectToAction("Login", "Account"); // Redirect to login page if staff code is not found in session
            } else
            {
                string staffCode = Session["StaffCode"].ToString(); // Retrieve staff code from session
                                                                    //string branchCode = Session["BranchCode"].ToString(); // Retrieve branch code from session

                DataSet ds = new DataSet();

                // Pass staff code and branch code to the method for fetching tests
                ds = await objbal.ListPendingVoucherAsyncSGS();

                Accountant objtr1 = new Accountant();
                List<Accountant> AddExpense1 = new List<Accountant>();

                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    Accountant objtn = new Accountant
                    {
                        VoucherId = row.IsNull("VoucherId") ? 0 : Convert.ToInt32(row["VoucherId"]),
                        VoucherCode = row.IsNull("VoucherCode") ? string.Empty : row["VoucherCode"].ToString(),
                        VendorName = row.IsNull("VendorName") ? string.Empty : row["VendorName"].ToString(),
                        Amount = row.IsNull("Amount") ? 0.0f : float.Parse(row["Amount"].ToString()),
                        AmountPaidTo = row.IsNull("StaffName") ? string.Empty : row["StaffName"].ToString(),
                        Description = row.IsNull("Description") ? string.Empty : row["Description"].ToString(),
                        PaymentMode = row.IsNull("PaymentMode") ? string.Empty : row["PaymentMode"].ToString(),
                        BankId = row.IsNull("BankId") ? 0 : Convert.ToInt32(row["BankId"]),
                        ReceiverBankAccountNumber = row.IsNull("ReceiverBankAccountNumber") ? 0 : Convert.ToInt64(row["ReceiverBankAccountNumber"].ToString()),

GSTEducationERP/Views/Accountant/AddBankPartialView.cshtml
@model GSTEducationERPLibrary.Accountant.Accountant

@{
    ViewBag.Title = "AddNewBankAccountAsyncAN";
   // Layout = "~/Views/Shared/_LayoutERP.cshtml";
}

<head>
    <script src="/Content/plugins/jquery/jquery.min.js" type="text/javascript"></script>
    <style>
        h2 {
            padding-top: 10px;
            margin-bottom: 8px;
            font-family: Verdana;
            font-weight: bold;
            font-size: medium;
            color: #33CCCC;
        }

        .btn-green:hover {
            color: white;
            background: #2b83cb;
        }

        .btn-black {
            color: white;
            background: rgb(169,169,169);
        }

        a {
            color: #13c6e6;
        }

        .btn-black:hover {
            background: black;
        }

        .addlogo {
            width: 65%;
            aspect-ratio: 3/2;
            object-fit: contain;
            /*mix-blend-mode: color-burn;*/
        }

        .sectionEditLink:hover {
            background-color: darkturquoise;
        }

        .card {
            padding-left: 20px;
            padding-right: 20px;
        }

        .form-group {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }

        label {
            /*margin-right: 10px;*/
            font: xx-small !important;
        }

        input {
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
    </style>
</head>
<body>

    @using (Html.BeginForm("AddNewBankAccountAsyncAN", "Accountant", new { @id = "AddBank", @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <br />
        <div class="card" style="width: 800px; border-left-width: 0px; padding-left: 50px; left: 52px; ">
            <div class="card-body">
                <h2>Add New Bank Account</h2>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BankName, "Bank Name:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.BankName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BankBrach, "Branch:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.BankBrach, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankBrach, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.AccountHolderName, "Account Holder Name:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.AccountHolderName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AccountHolderName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BankAccountNumber, "Account Number:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.IFSCCode, "IFSC Code:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.IFSCCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IFSCCode, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.MICRCode, "MICR Code:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.MICRCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MICRCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.AccountType, "Account Type", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.AccountType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AccountType, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BankAccountOpeningDate, "Account Opening Date:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.BankAccountOpeningDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankAccountOpeningDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BankAccountOpeningBalance, "Opening Balance:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.BankAccountOpeningBalance, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankAccountOpeningBalance, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BankAccountMinimumBalance, "Minimum Balance:", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.BankAccountMinimumBalance, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankAccountMinimumBalance, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="text-center pt-2 mb-2">
                    <button type="submit" id="submit" name="submit" class="btn btn-sm btn-success">Save</button>
                    <button type="button" name="clear" id="clear" class="btn btn-sm btn-warning" onclick="clearForm()">Clear</button>
                    <div class="text-left">
                        <a href="/Placement/ListAllCompanyAsyncPB" class="icon">
                            <video width="30" height="30" playsinline loop>
                                <source src="~/Content/Admin/icon/Back.mp4" type="video/mp4">
                            </video>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script>
        function clearForm() {
            document.getElementById("AddBank").reset();
        }
    </script>

</body>

GSTEducationERP/Views/Accountant/ListAllVouchersAsyncSGS.cshtml
@{
    ViewBag.Title = "ListAllVouchersAsyncSGS";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_LayoutERP.cshtml";
}



<html>
<head>
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <link href="~/Content/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Content/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <style>
        h2 {
            color: #64bbc9;
            font-weight: bold;
            font-size: 20px;
            margin-left: 17px;
            margin-bottom: -10px;
            font-family: sans-serif;
        }

        .dataTables_wrapper .btn-secondary {
            color: #235;
            background-color: transparent !important;
            border-color: transparent;
            font-size: x-large;
            margin: 0px !important;
        }

        .card-primary.card-outline-tabs > .card-header a.active {
            border-top: 3px solid #33CCCC;
        }

        a {
            color: #33CCCC;
        }

        .card.card-outline-tabs .card-header a:hover {
            color: #33CCCC;
        }

        .card-primary.card-outline-tabs > .card-header a.active, .card-primary.card-outline-tabs > .card-header a.active:hover {
            border-top: 3px solid #33CCCC;
        }

        .card-body {
            font-family: Calibri !important;
            padding-bottom: 0px !important;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        th {
            background-color: #33CCCC;
            color: #000;
            text-align: center !important;
        }

        td {
            text-align: center;
            color: black !important;
        }

        .table td {
            padding: 0px 0px 0px 0px !important;
            font-size: 14px !important;
        }

        .table th {
            padding: 5px 5px 4px 10px !important;
            font-size: 14px !important;
        }

        table.dataTable > thead .sorting:after, table.dataTable > thead .sorting:before {
            font-size: xx-small !important;
        }

        div.dataTables_wrapper div.dataTables_filter {
            /*margin-top: -40px !important;*/
        }

        div.dt-buttons {
            /*margin-top: -20px !important;*/
        }

        .btn-group > .btn:not(:last-child):not(.dropdown-toggle), .btn-group > .btn-group:not(:last-child) > .btn {
            padding-left: 5px !important;
            padding-right: 5px !important;
        }

        div.dataTables_wrapper div.dataTables_filter label {
            font-size: small !important;
        }

        div.dataTables_wrapper div.dataTables_filter input {
            height: 20px !important;
        }

        div.dataTables_wrapper div.dataTables_info {
            padding: 0px !important;
            font-size: small !important;
        }

        div.dataTables_wrapper div.dataTables_paginate ul.pagination {
            /* margin-top: -20px !important;*/
        }

        div.dataTables_wrapper div.dataTables_paginate {
            font-size: small !important;
        }

        .image-style {
            width: 35px;
            height: auto;
        }


        .icon-container {
            margin-top: 8px; /* Adjust the margin as needed */
        }
    </style>

</head>
<body>
    <br />


    <div class="card p-2">

        <!--<div class="row">
            <div class="col-md-6">
                <h2>  Test Managament </h2>
            </div>-->
        @*<button type="button" class="btn btn-block bg-gradient-info" value="AllProjects" onclick="location.href='@Url.Action("RegisterTestAsycTS", "Trainer")'"
                    style="width: 150px; height: 40px;">
                Add New Test
            </button>*@
        <!--<div class="col-md-6 text-right">

                <div class="col-2" id="addTestButton">
                    <a href="@Url.Action("RegisterTestAsycTS","Trainer")" class="video-link" title="Add Test">
                        <img src="~/Content/Admin/icon/Add.jpeg" class="image-style" />
                    </a>
                </div>
                <div class="col-2" id="assignTestButton" style="display:none;">
                    <a href="@Url.Action("RegisterAssignTestTS")" class="video-link" title="Assign Test">
                        <img src="~/Content/Admin/icon/Add.jpeg" class="image-style" />
                    </a>
                </div>
            </div>
        </div>-->

        <div class="row g-6">
            <div class="col-md-10 justify-content-lg-start">
                <h2>  Voucher Managament </h2>

            </div>


            <div class="col-2" id="addTestButton">
                <a href="@Url.Action("AddVoucherAsyncSGS")" class="video-link" title="Add Voucher">
                    <img src="~/Content/Admin/icon/Add.jpeg" class="image-style" />
                </a>
            </div>
            @*<div class="col-2" id="assignTestButton" style="display:none;">
                <a href="@Url.Action("RegisterAssignTestTS")" class="video-link" title="Assign Test">
                    <img src="~/Content/Admin/icon/Add.jpeg" class="image-style" />
                </a>
            </div>*@
        </div>
        <hr />
        <div class="card-body">

            <div class="container" style="margin-left:-10px">
                <div class="col-2">


                </div>
                <div class="row">

                    <div class="col-10">
                        <div class="card card-primary card-outline card-outline-tabs">
                            <div class="card-header p-0 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="pill" href="@Url.Action("ListVoucherAsyncSGS", "Accountant")" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true">Vouchers</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="pill" href="@Url.Action("ListPendingVoucherAsyncSGS", "Accountant")" role="tab" aria-controls="custom-tabs-four-profile" aria-selected="false">Pending Vouchers</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="pill" href="@Url.Action("ListCompletedVoucherAsyncSGS", "Accountant")" role="tab" aria-controls="custom-tabs-four-messages" aria-selected="false">Completed Vouchers</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>


                </div>

            </div>

            <div class="card-body">
                <div class="card card-primary card-outline card-outline-tabs p-2">
                    <div id="ExamList" class="icon-container"></div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/plugins/datatables/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-responsive/js/responsive.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-buttons/js/buttons.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/jszip/jszip.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/pdfmake/pdfmake.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/pdfmake/vfs_fonts.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-buttons/js/buttons.html5.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-buttons/js/buttons.print.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/datatables-buttons/js/buttons.colVis.min.js" type="text/javascript"></script>






    <script>
    jQuery(document).ready(function ($) {
        // Function to load tab content
        function loadTabContent(tabContentUrl) {
            $.ajax({
                url: tabContentUrl,
                type: 'GET',
                success: function (data) {
                    $('#ExamList').html(data);
                    var table = $('#ExamList table').DataTable({
                        "responsive": true,
                        "lengthChange": false,
                        "autoWidth": false,
                        "stateSave": true,
                        "buttons": [
                            {
                                extend: 'pdf',
                                text: '<img src="/Content/Admin/icon/pdf-file.png" title="pdf" alt="pdf" height="20" width="20" />',
                                titleAttr: 'PDF'
                            },
                            {
                                extend: 'excel',
                                text: '<img src="/Content/Admin/icon/xls-file.png" title="xls" alt="xls" height="20" width="20" />',
                                titleAttr: 'Excel'
                            },
                            {
                                extend: 'csv',
                                text: '<img src="/Content/Admin/icon/csv.jpg" title="CSV" alt="CSV" height="25" width="25" />',
                                titleAttr: 'CSV'
                            },
                            {
                                extend: 'copy',
                                text: '<img src="/Content/Admin/icon/copy.png" title="Copy" alt="Copy" height="20" width="20" />',
                                titleAttr: 'Copy'
                            },
                            {
                                extend: 'print',
                                text: '<img src="/Content/Admin/icon/printer.png" title="printer" alt="printer" height="20" width="20" />',
                                titleAttr: 'Print'
                            }
                        ]
                    });
                    table.buttons().container().appendTo('#ExamList .col-md-6:eq(0)');
                },
                error: function () {
                    alert('Error loading content.');
                }
            });
        }

        // Load the default tab content and simulate a click on the "All Test" tab
        var defaultTabUrl = '@Url.Action("ListVoucherAsyncSGS", "Accountant")';
        loadTabContent(defaultTabUrl);
        $('#allTestTabLink').click();

        // Event handler for tab links
        $('#custom-tabs-four-tab').on('click', '.nav-link', function (e) {
            e.preventDefault();
            var tabContentUrl = $(this).attr('href');
            loadTabContent(tabContentUrl);

    //        var activeTab = $(this).text().trim();
    //        if (activeTab === 'Regular') {
    //            $('#addTestButton').show();
    //            $('#assignTestButton').hide();
    //        } else if (activeTab === 'Refund') {
    //            $('#addTestButton').hide();
    //            $('#assignTestButton').show();
    //        } else {
				//$('#addTestButton').hide();
    //            $('#assignTestButton').hide();
    //        }
        });

        var defaultTabUrl = '@Url.Action("ListVoucherAsyncSGS", "Accountant")';
        loadTabContent(defaultTabUrl);
    });
    </script>













</body>
</html>