GSTEducationERP/Controllers/BindController.cs
using GSTEducationERPLibrary.Bind;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Collections.Specialized;
using System.Net.Http;



namespace GSTEducationERP.Controllers
{
    public class BindController : Controller
    {
        private readonly BALBind BALObj;

        public BindController()
        {
            BALObj = new BALBind();
        }
        public ActionResult Index()
        {
            return View();
        }
        public class BreadcrumbItem
        {
            public string Name { get; set; }
            public string Url { get; set; }
        }
        public async Task AllCourseBind()
        {
            Bind obj = new Bind();
            obj.BranchCode = Session["BranchCode"].ToString();
            DataSet ds1 = new DataSet();
            ds1 = await BALObj.AllCourseBind(obj);
            List<SelectListItem> AllCourseBind = new List<SelectListItem>();
            if (ds1.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow dr in ds1.Tables[0].Rows)
                {
                    AllCourseBind.Add(new SelectListItem
                    {
                        Text = dr["CourseName"].ToString(),
                        Value = dr["Coursecode"].ToString()
                    });
                }
            }
            ViewBag.AllCourseBind = AllCourseBind;

        }
        [HttpGet]
        public async Task<ActionResult> DetailStaffProfile()
        {
            if (Session["StaffCode"] == null)
            {
                return await Task.Run(() => RedirectToAction("Login", "Account"));
            }
            else
            {
                Bind ObjCo = new Bind();
                ObjCo.BranchCode = Session["BranchCode"].ToString();
                ObjCo.StaffCode = Session["StaffCode"].ToString();
                SqlDataReader dr;
                dr = await BALObj.StaffProfileAsync(ObjCo);
                while (dr.Read())
                {
                    ObjCo.StaffName = dr["StaffName"].ToString();
                    ObjCo.Photograph = dr["Photograph"].ToString();
                    ObjCo.StaffPosition = dr["StaffPosition"].ToString();
                    ObjCo.DesignationCurrent = dr["DesignationCurrent"].ToString();
                    ObjCo.DepartmentNameCurrent = dr["DepartmentNameCurrent"].ToString();
                    ObjCo.JoiningDate = dr["JoiningDate"].ToString();
                    ObjCo.GraduationName = dr["GraduationName"].ToString();
                    ObjCo.PostGraduationName = dr["PostGraduationName"].ToString();
                    ObjCo.BranchName = dr["BranchName"].ToString();
                    ObjCo.currentCity = dr["currentCity"].ToString();
                    ObjCo.SkillNames = dr["SkillNames"].ToString();

                }
                dr.Close();
                string Staffpostion = Session["StaffPositionId"].ToString();
                if (Staffpostion == "3")
                {
                    List<BreadcrumbItem> breadcrumbs = new List<BreadcrumbItem>
                    {
                    new BreadcrumbItem { Name = "TrainerDashboard", Url =Url.Action("TrainerDashboardAsyncTS","Trainer")},
                    new BreadcrumbItem { Name = "Profile", Url =  Url.Action("DetailStaffProfile")}
                    };

                    ViewBag.Breadcrumb = breadcrumbs;
                }
                else
                {
                    List<BreadcrumbItem> breadcrumbs = new List<BreadcrumbItem>
                    {
                    new BreadcrumbItem { Name = "CoordinatorDashboard", Url = Url.Action("CoordinatorDashboardPRAsync","Coordinator")},
                    new BreadcrumbItem { Name = "Profile", Url =  Url.Action("DetailStaffProfile")}
                    };

                    ViewBag.Breadcrumb = breadcrumbs;

                }
                return await Task.Run(() => View("DetailStaffProfile", ObjCo));
            }
        }

        public async Task<ActionResult> DetailsStaffProfileAsync()
        {
            if (Session["StaffCode"] == null)
            {
                return await Task.Run(() => RedirectToAction("Login", "Account"));

            }
            else
            {
                Bind ObjCo = new Bind();
                ObjCo.BranchCode = Session["BranchCode"].ToString();
                ObjCo.StaffCode = Session["StaffCode"].ToString();
                SqlDataReader dr;
                dr = await BALObj.StaffProfileAsync(ObjCo);
                while (dr.Read())
                {
                    ObjCo.StaffName = dr["StaffName"].ToString();
                    ObjCo.StaffPosition = dr["StaffPosition"].ToString();
                    ObjCo.CourseName = dr["CourseName"].ToString();
                    ObjCo.CourseType = dr["CourseType"].ToString();
                    ObjCo.DOB = dr["DOB"].ToString();
                    ObjCo.PhoneNo = dr["PhoneNo"].ToString();
                    ObjCo.EMail = dr["Email"].ToString();
                    ObjCo.CurrentAddress = dr["CurrentAddress"].ToString();
                    ObjCo.currentCity = dr["currentCity"].ToString();
                    ObjCo.CurrentPinCode = dr["CurrentPinCode"].ToString();
                    ObjCo.PermanentAddress = dr["PermanentAddress"].ToString();
                    ObjCo.PermanentCity = dr["PermanentCity"].ToString();
                    ObjCo.PermanentPinCode = dr["PermanentPinCode"].ToString();
                    ObjCo.MaritalStatus = dr["MaritalStatus"].ToString();
                    ObjCo.Nationality = dr["Nationality"].ToString();
                    ObjCo.BloodGroup = dr["BloodGroup"].ToString();
                    ObjCo.Gender = dr["Gender"].ToString();
                    ObjCo.AadharCardNo = dr["AadharCardNo"].ToString();
                    ObjCo.PanCardNo = dr["PanCardNo"].ToString();
                    ObjCo.EmergencyContactName = dr["EmergencyContactName"].ToString();
                    ObjCo.EmergencyContactNo = dr["EmergencyContactNo"].ToString();
                    ObjCo.EmergencyContactAddress = dr["EmergencyContactAddress"].ToString();
                    ObjCo.FatherName = dr["FatherName"].ToString();
                    ObjCo.FatherContactNo = dr["FatherContactNo"].ToString();
                    ObjCo.MotherName = dr["MotherName"].ToString();
                    ObjCo.MotherContactNo = dr["MotherContactNo"].ToString();
                    ObjCo.BankName = dr["BankName"].ToString();
                    ObjCo.AccountHolderName = dr["AccountHolderName"].ToString();
                    ObjCo.AccountNumber = dr["AccountNumber"].ToString();
                    ObjCo.BankBranchName = dr["BankBranchName"].ToString();
                    ObjCo.IFSCCode = dr["IFSCCode"].ToString();
                    ObjCo.MICRCode = dr["MICRCode"].ToString();
                    ObjCo.JoiningDate = dr["JoiningDate"].ToString();
                    ObjCo.OfficialEmailId = dr["OfficialEmailId"].ToString();
                    ObjCo.Password = dr["Password"].ToString();
                    ObjCo.SSCYear = dr["SSCYear"].ToString();
                    ObjCo.HSCYear = dr["HSCYear"].ToString();
                    ObjCo.DiplomaYear = dr["DiplomaYear"].ToString();
                    ObjCo.GraduationName = dr["GraduationName"].ToString();
                    ObjCo.GraduationYear = dr["GraduationYear"].ToString();
                    ObjCo.PostGraduationName = dr["PostGraduationName"].ToString();
                    ObjCo.PostGraduationYear = dr["PostGraduationYear"].ToString();
                    ObjCo.IndustryName = dr["InduastryName"].ToString();
                    ObjCo.DesignationName = dr["DesignationName"].ToString();
                    ObjCo.DepartmentName = dr["DepartmentName"].ToString();
                    ObjCo.CTC = dr["CTC"].ToString();
                    ObjCo.Experience = dr["Experience"].ToString();
                    ObjCo.TotalExperienceOfDesignation = dr["TotalExperienceOfDesignation"].ToString();
                    ObjCo.JobType = dr["JobType"].ToString();
                    ObjCo.CompanyName = dr["CompanyName"].ToString();
                    ObjCo.Photograph = dr["Photograph"].ToString();
                    ObjCo.BranchName = dr["BranchName"].ToString();
                    ObjCo.DepartmentNameCurrent = dr["DepartmentNameCurrent"].ToString();
                    ObjCo.DesignationCurrent = dr["DesignationCurrent"].ToString();
                    ObjCo.SkillNames = dr["SkillNames"].ToString();


                }
                dr.Close();
                return await Task.Run(() => PartialView(ObjCo));
            }
        }
        public async Task<ActionResult> DetailsStaffDocumetAsync()
        {
            if (Session["StaffCode"] == null)
            {
                return await Task.Run(() => RedirectToAction("Login", "Account"));

            }
            else
            {
                Bind ObjCo = new Bind();
                ObjCo.StaffCode = Session["StaffCode"].ToString();
                SqlDataReader dr;
                dr = await BALObj.StaffDocumetAsync(ObjCo);
                while (dr.Read())
                {
                    ObjCo.PanCard = dr["PanCard"].ToString();
                    ObjCo.AadharCard = dr["AadharCard"].ToString();
                    ObjCo.SSC = dr["SSC"].ToString();
                    ObjCo.HSC = dr["HSC"].ToString();
                    ObjCo.Diploma = dr["Diploma"].ToString();
                    ObjCo.Graduation = dr["Graduation"].ToString();
                    ObjCo.PostGraduation = dr["PostGraduation"].ToString();
                    ObjCo.RelievingLetter = dr["RelievingLetter"].ToString();
                    ObjCo.SalarySlip = dr["SalarySlip"].ToString();

GSTEducationERP/Views/Coordinator/AddFeeFollowUpDetailsAsyncRS.cshtml
@model GSTEducationERPLibrary.Coordinator.Coordinator

@*@{
        ViewBag.Title = "ViewFeeFollowupDetailsAsyncRs";
        //Layout = "~/Views/Shared/_Layout.cshtml";
    }*@


<html>
<head>
    <script src="~/Content/plugins/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.3/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.3/dist/sweetalert2.all.min.js"></script>

    <link rel="stylesheet" href="~/Content/plugins/toastr/toastr.min.css" />
    <script src="~/Content/plugins/toastr/toastr.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/Content/plugins/moment/moment.min.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#timepicker').datetimepicker({
                format: 'LT'
            });

            $('#reservationdate').datetimepicker({
                format: 'YYYY-MM-DD',
                minDate: moment().startOf('day')
            });

            $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });
    </script>
    <script>
        $(document).ready(function () {
            $('#saveButton').click(async function (event) {
                debugger;
                event.preventDefault();
                var staffCode = $('#StaffCode').val();
                var followUpNote = $('#FollowUpNote').val();
                var nextInstallmentDate = $('#NextInstallmentDate').val();
                var nextFollowUpDate = $('#NextFollowUpDate').val();
                var statusId = $('#StatusId').val();

                var studentCode = $('#StudentCode').val().trim();


                if (staffCode.trim() === '' || followUpNote.trim() === '' || nextInstallmentDate.trim() === '' || nextFollowUpDate.trim() === '' || statusId.trim() === '') {
                    Swal.fire('Error', 'Please fill in all fields.', 'error');
                    return;
                }

                Swal.fire({
                    title: 'Are you sure?',
                    text: 'You are about to save your followUp.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, save it!'
                }).then(async (result) => {
                    if (result.isConfirmed) {
                        var formData = new FormData();
                        formData.append('StudentCode', studentCode);
                        formData.append('StaffCode', staffCode);
                        formData.append('FollowUpNote', followUpNote);
                        formData.append('NextInstallmentDate', nextInstallmentDate);
                        formData.append('NextFollowUpDate', nextFollowUpDate);
                        formData.append('StatusId', statusId);

                        try {
                            debugger;
                            var response = await fetch('/Coordinator/AddFeeFollowUpDetailsAsyncRS', {
                                method: 'POST',
                                body: formData
                            });

                            if (response.ok) {
                                displayToast('Data Saved Successfully.', 'success');
                                window.location.href = '/Coordinator/ListAddedFeeFollowupAsyncRs';
                            } else {
                                displayToast('Error saving followup data. Please try again.', 'error');
                            }
                        } catch (error) {
                            console.error('Error:', error);
                            displayToast('An unexpected error occurred. Please try again later.', 'error');
                        }
                    }
                });
            });
        });

        function displayToast(message, type) {
            toastr[type](message);
        }

        toastr.options = {
            closeButton: true,
            progressBar: true,
            positionClass: 'toast-top-right',
            showMethod: 'slideDown',
            timeOut: 4000
        };
    </script>

    <script>
        $(document).ready(function () {

            $('#clearButton').click(function () {

                $('input[type=text], input[type=email], textarea, select').val('');


                $('.datepicker').val('');
                var presentDate = new Date().toISOString().slice(0, 10);
                $('input[type=date]').val(presentDate);


                displayToast('Form cleared successfully.', 'info');
            });
        });

    </script>
    <script>
        document.getElementById('NextFollowUpDate').addEventListener('change', function () {
            var nextInstallmentDate = document.getElementById('NextInstallmentDate').value;
            var nextFollowUpDate = this.value;

            if (new Date(nextFollowUpDate) <= new Date(nextInstallmentDate)) {
                alert('Next Follow-Up Date must be after Next Installment Date');
                this.value = '';
            }
        });
    </script>

    <style>
        /* Add a custom style to adjust the width */
        .form-control.datetimepicker-input {
            width: 50%; /* Set the desired width */
        }
    </style>


</head>
<body>
    <h2> Add fee FollowUp </h2>
    <div>
        <hr />
        <br />
        <div class="card " style="padding:5px;margin-right:20px;margin-left:10px; margin-top:-15px">

            <div hidden>
                @Html.DisplayNameFor(model => model.StudentId)
                @Html.DisplayFor(model => model.StudentId)
            </div>
            <input type="hidden" id="StudentCode" value="@Model.StudentCode" />

            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Student Name</label>
                <div class="col-md-6">
                    @Model.FullName
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Remaining Fee</label>
                <div class="col-md-6">
                    @Model.RemainingFee
                </div>
            </div>


            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Installment Amount</label>
                <div class="col-md-6">
                    @Model.Amount
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Follow Up taken By</label>
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.StaffCode, new SelectList(ViewBag.StaffList, "Value", "Text"), "---Select---", new { @class = "form-control", id = "StaffCode" })
                    @Html.ValidationMessageFor(model => model.StaffCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Status</label>
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.StatusId, new SelectList(ViewBag.StatusList, "Value", "Text"), "---Select---", new { @class = "form-control", id = "StatusId" })
                    @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Follow-Up Note</label>
                <div class="col-md-6">
                    @Html.TextAreaFor(model => model.FollowUpNote, new { @class = "form-control", rows = "3", maxlength = "250", id = "FollowUpNote", placeholder = "Please enter your text here" })
                    @Html.ValidationMessageFor(model => model.FollowUpNote, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Next Installment Date</label>
                <div class="col-md-6">
                    <input type="date" class="form-control col-md-12 datepicker" id="NextInstallmentDate" name="NextInstallmentDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" min="@DateTime.Now.ToString("yyyy-MM-dd")" required />
                    @Html.ValidationMessageFor(model => model.NextInstallmentDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-md-4" style="margin-left: 40px;">Next Follow-Up Date</label>
                <div class="col-md-6">
                    <input type="date" class="form-control col-md-12 datepicker" id="NextFollowUpDate" name="NextFollowUpDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" min="@Model.NextInstallmentDate.ToString("yyyy-MM-dd")" required />
                    @Html.ValidationMessageFor(model => model.NextFollowUpDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-12 text-center">
                <input type="button" class="btn btn-success" value="Save" id="saveButton" style="margin-right:20px" />
                <input type="button" class="btn btn-warning" value="Clear" id="clearButton" style=" margin-right:20px" />
            </div>

        </div>
    </div>
    <button class="close text-danger" data-dismiss="modal" style="position: absolute; top: 8px; right: 8px;">&times;</button>





</body>
</html>

GSTEducationERP/Views/Coordinator/ListAssignBatchAsyncST.cshtml
@model GSTEducationERPLibrary.Coordinator.Coordinator

@{
    ViewBag.Title = "ListAssignBatchAsyncST";
}

<style>
    .btn-custom {
        background-color: #ffcc00;
        color: #ffffff;
        border: 2px solid #ffcc00;
        border-radius: 8px;
        padding: 10px 20px;
        text-decoration: none;
        transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;
    }

        .btn-custom:hover {
            background-color: #ff9900;
            color: #ffffff;
            border-color: #ff9900;
        }
    h3 {
        color: #64bbc9;
        font-weight: bold;
        font-size: 30px;
        margin-left: 17px;
        margin-bottom: -10px;
        font-family: sans-serif;
    }
</style>
<html lang="en" style="height: auto;">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>

    <script src="~/Content/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/plugins/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/Coordinator/css/ToolTips.css" rel="stylesheet" />

</head>




<body>
    @*//POPUP*@

    <div id="partialModal1" class="modal" tabindex="-1" role="dialog" aria-labelledby="BatchModalLabel" style="position:center">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title " id="BatchModalLabel">Batch Schedule Details</h3>
                    <button class="close text-danger" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body1">
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <div id="partialModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="BatchModalLabel" style="position: center; padding: 15px; margin-right: 800px; margin-left: -180px; margin-top: -15px">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="margin-right: 350px; margin-left: 150px; width: 640px;">
                <!-- Adjust width as needed -->
                <div class="modal-header">
                    <h3 class="modal-title " id="BatchModalLabel"> Edit Batch Schedule</h3>
                    <button class="close text-danger" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body" style="margin-right: 400px; margin-left: 200px;">
                    <!-- Your modal body content goes here -->
                </div>
                <div class="modal-footer">
                    <!-- Your modal footer content goes here -->
                </div>
            </div>
        </div>
    </div>
   
    <div class="modal" id="StudentModal">
        <div class="modal-dialog" style="background-color: white;">
            <div class="modal-content" style="background-color: white;">
                <h1 class="text-info modal-title">Student List</h1>
            </div>
        </div>
    </div>

    <div class="card mt-4" style=" margin-top: 0px !important">
        <div class="card-body">
            <table id="BatchData" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th hidden>
                            Schedule Id
                        </th>
                        <th hidden>
                            BatchCode
                        </th>
                        <th>
                            Batch
                        </th>
                        <th>
                            Course
                        </th>
                        <th>
                            Trainer
                        </th>
                        <th>
                            Lab
                        </th>
                        <th>
                            Student
                        </th>

                        <th>
                            Schedule Date
                        </th>
                        <th>
                            Start Date
                        </th>
                        <th>
                            Start Time
                        </th>
                        <th>
                            End Time
                        </th>
                        <th>
                            Status
                        </th>

                        <th>Action </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.lstBatchData)
                    {
                        <tr>
                            <td hidden>
                                @Html.DisplayFor(modelItem => item.ScheduleId)
                            </td>
                            <td hidden>
                                @Html.DisplayFor(modelItem => item.BatchCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BatchName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CourseName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StaffName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LabName)
                            </td>
                            <td style="text-align: center;">
                                <u>
                                    <a href="#" class="icon" data-id="@item.BatchCode" data-url="@Url.Action("BatchAllStudentDetailsAsyncST", "Bind", new { batchcode = item.BatchCode  })"
                                       data-toggle="modal" data-target="#StudentModal" title="Student List">
                                        @item.NoOfStudent
                                    </a>
                                </u>
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.BatchScheduleDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartDate)
                            </td>
                            <td>
                                @Html.Raw(item.StartTime.ToString("h:mm:ss tt"))
                            </td>
                            <td>
                                @{
                                    DateTime endTimeWithAdditional15Minutes = item.EndTime.AddMinutes(15);
                                }
                                @Html.Raw(endTimeWithAdditional15Minutes.ToString("h:mm:ss tt"))
                            </td>
                            <td>
                                @if (item.Status == "Assigned")
                                {
                                    <span class="badge bg-green">@Html.DisplayFor(modelItem => item.Status)</span>
                                }
                            </td>
                            <td>
                                <a class="ScheduleDetailes" href="javascript:;" data-id="@item.ScheduleId" tooltip="View DetailsBatchScheduleAsyncST " flow="down">
                                    <video width="35" height="35" playsinline loop>
                                        <source src="~/Content/Admin/icon/view.mp4" type="video/mp4">
                                    </video>
                                </a>
                                <a class="ScheduleUpdate" href="javascript:;" data-id="@item.ScheduleId" tooltip="Update DetailsBatchScheduleAsyncST " flow="down">
                                    <video width="35" height="35" playsinline loop>
                                        <source src="~/Content/Admin/icon/Edit Details.mp4" type="video/mp4">
                                    </video>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
    <script type="text/javascript">
        jQuery.noConflict();
        jQuery(document).ready(function ($) {
            $(".ScheduleDetailes").click(function () {
                var $buttonClicked = $(this);
                var id = $buttonClicked.data('id'); // Use data() to get 'data-id' attribute value
                $.ajax({
                    type: "GET",
                    url: "/Coordinator/DetailsBatchScheduleAsyncST",
                    data: { ScheduleId: id },
                    contentType: "application/json; charset=utf-8",
                    dataType: "html",
                    success: function (response) {
                        $("#partialModal1 .modal-body1").html(response); // Simplified selector
                        $("#partialModal1").modal('show');
                    },
                    error: function (xhr, status, error) {
                        alert("Error: " + error); // Alert the error message
                    }
                });
            });
            $(".ScheduleUpdate").click(function () {
                var $buttonClicked = $(this);
                var id = $buttonClicked.data('id'); // Use data() to get 'data-id' attribute value
                $.ajax({
                    type: "GET",
                    url: "/Coordinator/UpdateBatchScheduleAsyncST",
                    data: { ScheduleId: id },
                    contentType: "application/json; charset=utf-8",
                    dataType: "html",
                    success: function (response) {
                        $("#partialModal .modal-body").html(response); // Simplified selector
                        $("#partialModal").modal('show');
                    },
                    error: function (xhr, status, error) {
                        alert("Error: " + error); // Alert the error message
                    }
                });
            });
            $('#BatchData').on('click', '.icon', function () {
                var BatchCode = $(this).data('id');
                var url = $(this).data('url');
                // Make an AJAX call to load the content of DemoDetailssection view
                $.ajax({
                    url: url,
                    type: 'GET',
                    success: function (data) {
                        // Update the modal body with the content of DemoDetailssection view
                        $("#StudentModal").find(".modal-content").html(data);
                        // Show the modal
                        $('#StudentModal').modal('show');
                    }
                });
            });
        });
    </script>
</body>
</html>